### PR TITLE
Fix: Cannot read property 'body' of undefined" when using "morgue put

### PR DESCRIPTION
**Pull request by nsculli7**
This uses logic suggested by @amadden80 .  We look through the configured post endpoints and select the first secured (`https` protocol) endpoint.

### CODE REVIEW

**Review by camlorn — CHANGES_REQUESTED** [review]
It looks like this will fail if only insecure endpoints are available. Is that actually the case?

**Comment by scull7** [comment]
Are we allowing insecure endpoints? If not, then should I throw a specific error?

**Comment by nsculli7** [comment]
Are we allowing insecure endpoints? If not, then should I throw a specific error?

**Comment by konraddysput** [comment]
@nsculli7 yes - test/dev instances/on-premise self generated certs... etc

**Comment by camlorn** [comment]
Insecure endpoints can show up if the service is on-prem (e.g. localhost) or if the service has self-signed certs.  The way Morgue handles the latter case is through `-k`, but self-signed scerts should show up as https urls.  Approving these changes as I thought we came to the conclusion that it's fine over slack, and it looks like I never signed off.

**Review by camlorn — APPROVED** [review]

**Pull request merged**
